# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myna < Formula
  desc "Myna CLI - The Postman for AWS services"
  homepage "https://jpalaniselvam.github.io/myna"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.2.0/myna_Darwin_x86_64.tar.gz"
      sha256 "a0d1958d4ba32cc83f6b9baed52563bbe4c944f65c83c7fe011379188952b9db"

      define_method(:install) do
        bin.install "myna"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.2.0/myna_Darwin_arm64.tar.gz"
      sha256 "80892c4dc1c59926c951c6886bc2cac48d7af43a499874df66851ba22a498e58"

      define_method(:install) do
        bin.install "myna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.2.0/myna_Linux_x86_64.tar.gz"
      sha256 "86682a1c574e6ad7e4f97b4ce4ac3c715d06b54d23a536f4e899314d7bf74dff"
      define_method(:install) do
        bin.install "myna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.2.0/myna_Linux_arm64.tar.gz"
      sha256 "c49d878c7324062b6ea3a2cb82a209fab311071a82fd0d5b8db7c85577c00a68"
      define_method(:install) do
        bin.install "myna"
      end
    end
  end
end
