# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myna < Formula
  desc "Myna CLI - The Postman for AWS services"
  homepage "https://jpalaniselvam.github.io/myna"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.1.0/myna_Darwin_x86_64.tar.gz"
      sha256 "891d22c22c0c37adc4cdd11f59dac7560039eaea433105d8cc244faa9b324f7d"

      def install
        bin.install "myna"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.1.0/myna_Darwin_arm64.tar.gz"
      sha256 "13859b717d1b7c396b2dd19677e9fb2be5e0166362d15982b49a338699c167e1"

      def install
        bin.install "myna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.1.0/myna_Linux_x86_64.tar.gz"
      sha256 "b34816c93d7e43904e0fbdcd5fbfc9a8926ccb0f887cdf935a393ff694d1a5bf"
      def install
        bin.install "myna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpalaniselvam/myna/releases/download/v0.1.0/myna_Linux_arm64.tar.gz"
      sha256 "ceaeef292917bca7b517cba711e1b9b5505e782d7506242d48b5c6316bcab83b"
      def install
        bin.install "myna"
      end
    end
  end
end
